# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks

permalink: :title.html
relative_permalinks: true

# Setup
title:            Mafalda Macx
tagline:          Pol√≠tica computacional
paginate:         4
absoluteurl:              https://mafaldamacx.github.io/blog/
baseurl:          /blog/
author:
  name:           Mafalda Macx
  url:            https://mafaldamacx.github.io
  email:          mafaldamacx@yahoo.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
